# sources_extra.py — 财报 / 研报 / 白皮书 / 政策 / 论文 / 数据 / 公告等补充源
from urllib.parse import quote


def _gnews_cn(query):
    return (
        "https://news.google.com/rss/search?q="
        f"{quote(query)}&hl=zh-CN&gl=CN&ceid=CN:zh-Hans"
    )


def _gnews_en(query):
    return (
        "https://news.google.com/rss/search?q="
        f"{quote(query)}&hl=en-US&gl=US&ceid=US:en"
    )


_GNEWS_US = (
    "https://news.google.com/rss/search?q=site:{domain}+when:7d"
    "&hl=en-US&gl=US&ceid=US:en"
)

EXTRA_SOURCES = [
    # ---------- 政策文件 ----------
    {
        "name": "China Gov Policy News",
        "name_cn": "中国政府网·政策",
        "rss": _gnews_cn("site:www.gov.cn (政策 OR 通知 OR 意见 OR 办法) when:14d"),
        "icon": "https://www.gov.cn/favicon.ico",
        "category": "政策文件",
        "doc_type": "policy",
        "domain": "geopolitics",
        "country": "中国",
        "priority": 1,
        "description": "中国政府网政策文件与通知线索",
    },
    {
        "name": "NDRC News",
        "name_cn": "国家发改委",
        "rss": _gnews_cn("site:ndrc.gov.cn (通知 OR 政策 OR 发布) when:30d"),
        "icon": "https://www.ndrc.gov.cn/favicon.ico",
        "category": "政策文件",
        "doc_type": "policy",
        "domain": "macro",
        "country": "中国",
        "priority": 1,
        "description": "发展改革委政策与规划动态",
    },
    {
        "name": "MIIT Policy",
        "name_cn": "工信部政策",
        "rss": _gnews_cn("site:miit.gov.cn (通知 OR 公告 OR 政策) when:30d"),
        "icon": "https://www.miit.gov.cn/favicon.ico",
        "category": "政策文件",
        "doc_type": "policy",
        "domain": "industry",
        "country": "中国",
        "priority": 1,
        "description": "工业和信息化部产业政策",
    },
    {
        "name": "PBOC Policy",
        "name_cn": "中国人民银行",
        "rss": _gnews_cn("site:pbc.gov.cn (公告 OR 通知 OR 政策) when:30d"),
        "icon": "http://www.pbc.gov.cn/favicon.ico",
        "category": "政策文件",
        "doc_type": "policy",
        "domain": "macro",
        "country": "中国",
        "priority": 1,
        "description": "央行货币政策与监管动态",
    },
    {
        "name": "White House Briefing",
        "name_cn": "白宫简报",
        "rss": "https://www.whitehouse.gov/news/feed/",
        "icon": "https://www.whitehouse.gov/favicon.ico",
        "category": "政策文件",
        "doc_type": "policy",
        "domain": "geopolitics",
        "country": "美国",
        "priority": 1,
        "description": "美国白宫新闻与政策表态",
    },
    {
        "name": "US Federal Register",
        "name_cn": "美国联邦公报",
        "rss": _gnews_en(
            'site:federalregister.gov (rule OR notice OR "executive order") when:14d'
        ),
        "icon": "https://www.federalregister.gov/favicon.ico",
        "category": "政策文件",
        "doc_type": "policy",
        "domain": "geopolitics",
        "country": "美国",
        "priority": 2,
        "description": "美国联邦法规与行政命令线索",
    },
    {
        "name": "EU Policy Tracker",
        "name_cn": "欧盟政策动态",
        "rss": _gnews_en(
            "site:ec.europa.eu (regulation OR directive OR decision OR proposal) when:14d"
        ),
        "icon": "https://european-union.europa.eu/favicon.ico",
        "category": "政策文件",
        "doc_type": "policy",
        "domain": "geopolitics",
        "country": "国际",
        "priority": 2,
        "description": "欧盟委员会政策与立法线索",
    },
    # ---------- 数据发布 ----------
    {
        "name": "NBS China",
        "name_cn": "国家统计局",
        "rss": _gnews_cn(
            "site:stats.gov.cn (数据 OR 公布 OR CPI OR PPI OR GDP) when:30d"
        ),
        "icon": "http://www.stats.gov.cn/favicon.ico",
        "category": "数据发布",
        "doc_type": "data",
        "domain": "macro",
        "country": "中国",
        "priority": 1,
        "description": "中国宏观与行业统计数据发布",
    },
    {
        "name": "BLS News",
        "name_cn": "美国劳工统计局",
        "rss": "https://www.bls.gov/feed/bls_latest.rss",
        "icon": "https://www.bls.gov/favicon.ico",
        "category": "数据发布",
        "doc_type": "data",
        "domain": "macro",
        "country": "美国",
        "priority": 1,
        "description": "美国就业、通胀等劳工数据",
    },
    {
        "name": "BEA News",
        "name_cn": "美国经济分析局",
        "rss": "https://www.bea.gov/rss/news_releases.xml",
        "icon": "https://www.bea.gov/favicon.ico",
        "category": "数据发布",
        "doc_type": "data",
        "domain": "macro",
        "country": "美国",
        "priority": 1,
        "description": "美国 GDP、贸易等国民经济核算",
    },
    {
        "name": "IEA Data & Stats",
        "name_cn": "IEA·数据与统计",
        "rss": _gnews_en(
            'site:iea.org (statistics OR data OR "monthly oil" OR inventory) when:30d'
        ),
        "icon": "https://www.iea.org/favicon.ico",
        "category": "数据发布",
        "doc_type": "data",
        "domain": "energy",
        "country": "国际",
        "priority": 2,
        "description": "国际能源署数据与月报线索",
    },
    # ---------- 财报 / 公司公告 ----------
    {
        "name": "SEC Press",
        "name_cn": "美国SEC新闻",
        "rss": "https://www.sec.gov/news/pressreleases.rss",
        "icon": "https://www.sec.gov/favicon.ico",
        "category": "公司公告",
        "doc_type": "announcement",
        "domain": "macro",
        "country": "美国",
        "priority": 1,
        "description": "美国证监会新闻稿与执法动态",
    },
    {
        "name": "SEC 8-K Current",
        "name_cn": "美股重大事项(8-K)",
        "rss": (
            "https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent"
            "&type=8-K&owner=include&count=40&output=atom"
        ),
        "icon": "https://www.sec.gov/favicon.ico",
        "category": "公司公告",
        "doc_type": "announcement",
        "domain": "industry",
        "country": "美国",
        "priority": 1,
        "description": "美股公司重大事项即时披露",
    },
    {
        "name": "SEC Earnings Filings",
        "name_cn": "美股财报提交",
        "rss": _gnews_en(
            'site:sec.gov (10-K OR 10-Q OR "earnings release") when:14d'
        ),
        "icon": "https://www.sec.gov/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "industry",
        "country": "美国",
        "priority": 1,
        "description": "美股定期报告与财报线索",
    },
    {
        "name": "SA Earnings Transcripts",
        "name_cn": "Seeking Alpha·财报电话会",
        "rss": "https://seekingalpha.com/sector/transcripts.xml",
        "icon": "https://seekingalpha.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "industry",
        "country": "美国",
        "priority": 1,
        "description": "美股财报电话会实录线索",
    },
    {
        "name": "Big Tech Earnings",
        "name_cn": "科技巨头财报",
        "rss": _gnews_en(
            '(Apple OR Microsoft OR Google OR Alphabet OR Amazon OR Meta OR "NVIDIA" OR Tesla) '
            '(earnings OR "quarterly results" OR "Q1" OR "Q2" OR "Q3" OR "Q4") when:30d'
        ),
        "icon": "https://news.google.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "美国",
        "priority": 1,
        "description": "苹果/微软/谷歌/亚马逊/Meta/英伟达/特斯拉财报",
    },
    {
        "name": "AI Cloud Earnings",
        "name_cn": "AI与云厂商财报",
        "rss": _gnews_en(
            '(OpenAI OR Anthropic OR "Microsoft Azure" OR Snowflake OR Palantir OR '
            'Databricks OR Cloudflare OR "ServiceNow" OR Adobe OR Oracle) '
            '(earnings OR "quarterly results" OR funding OR revenue) when:30d'
        ),
        "icon": "https://news.google.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "美国",
        "priority": 1,
        "description": "AI、云与软件平台公司业绩线索",
    },
    {
        "name": "Semiconductor Earnings",
        "name_cn": "半导体财报",
        "rss": _gnews_en(
            '(TSMC OR ASML OR Broadcom OR AMD OR Intel OR Qualcomm OR "Samsung Electronics" OR '
            'Micron OR "Applied Materials" OR ARM OR "Texas Instruments") '
            '(earnings OR "quarterly results" OR "Q1" OR "Q2" OR "Q3" OR "Q4") when:30d'
        ),
        "icon": "https://news.google.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "国际",
        "priority": 1,
        "description": "台积电/ASML/博通/AMD/英特尔等半导体财报",
    },
    {
        "name": "Internet Platform Earnings",
        "name_cn": "互联网平台财报",
        "rss": _gnews_en(
            '(Netflix OR Uber OR Airbnb OR Spotify OR Snap OR Pinterest OR "Booking Holdings" OR '
            'Shopify OR Block OR PayPal OR eBay) '
            '(earnings OR "quarterly results") when:30d'
        ),
        "icon": "https://news.google.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "美国",
        "priority": 1,
        "description": "流媒体、出行、电商与支付平台财报",
    },
    {
        "name": "China Tech Earnings",
        "name_cn": "中国科技互联网财报",
        "rss": _gnews_cn(
            "(腾讯 OR 阿里巴巴 OR 美团 OR 京东 OR 百度 OR 网易 OR 拼多多 OR 小米 OR 字节 OR 快手 OR 哔哩哔哩) "
            "(财报 OR 季报 OR 业绩 OR 营收) when:30d"
        ),
        "icon": "https://news.google.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "中国",
        "priority": 1,
        "description": "中国互联网与科技公司业绩披露",
    },
    {
        "name": "China Chip Earnings",
        "name_cn": "中国半导体财报",
        "rss": _gnews_cn(
            "(中芯国际 OR 华为 OR 海光 OR 寒武纪 OR 韦尔股份 OR 北方华创 OR 长电科技 OR 澜起科技) "
            "(财报 OR 季报 OR 业绩 OR 营收) when:30d"
        ),
        "icon": "https://news.google.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "中国",
        "priority": 1,
        "description": "中国半导体与算力相关公司业绩",
    },
    {
        "name": "AAPL Earnings SA",
        "name_cn": "苹果·Seeking Alpha",
        "rss": "https://seekingalpha.com/api/sa/combined/AAPL.xml",
        "icon": "https://seekingalpha.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "美国",
        "priority": 2,
        "description": "苹果公司分析与财报相关动态",
    },
    {
        "name": "MSFT Earnings SA",
        "name_cn": "微软·Seeking Alpha",
        "rss": "https://seekingalpha.com/api/sa/combined/MSFT.xml",
        "icon": "https://seekingalpha.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "美国",
        "priority": 2,
        "description": "微软公司分析与财报相关动态",
    },
    {
        "name": "NVDA Earnings SA",
        "name_cn": "英伟达·Seeking Alpha",
        "rss": "https://seekingalpha.com/api/sa/combined/NVDA.xml",
        "icon": "https://seekingalpha.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "美国",
        "priority": 2,
        "description": "英伟达公司分析与财报相关动态",
    },
    {
        "name": "GOOGL Earnings SA",
        "name_cn": "谷歌·Seeking Alpha",
        "rss": "https://seekingalpha.com/api/sa/combined/GOOGL.xml",
        "icon": "https://seekingalpha.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "美国",
        "priority": 2,
        "description": "Alphabet/谷歌分析与财报相关动态",
    },
    {
        "name": "META Earnings SA",
        "name_cn": "Meta·Seeking Alpha",
        "rss": "https://seekingalpha.com/api/sa/combined/META.xml",
        "icon": "https://seekingalpha.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "美国",
        "priority": 2,
        "description": "Meta 分析与财报相关动态",
    },
    {
        "name": "AMZN Earnings SA",
        "name_cn": "亚马逊·Seeking Alpha",
        "rss": "https://seekingalpha.com/api/sa/combined/AMZN.xml",
        "icon": "https://seekingalpha.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "美国",
        "priority": 2,
        "description": "亚马逊分析与财报相关动态",
    },
    {
        "name": "TSM Earnings SA",
        "name_cn": "台积电·Seeking Alpha",
        "rss": "https://seekingalpha.com/api/sa/combined/TSM.xml",
        "icon": "https://seekingalpha.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "国际",
        "priority": 2,
        "description": "台积电分析与财报相关动态",
    },
    {
        "name": "AVGO Earnings SA",
        "name_cn": "博通·Seeking Alpha",
        "rss": "https://seekingalpha.com/api/sa/combined/AVGO.xml",
        "icon": "https://seekingalpha.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "美国",
        "priority": 2,
        "description": "博通分析与财报相关动态",
    },
    {
        "name": "BABA Earnings SA",
        "name_cn": "阿里巴巴·Seeking Alpha",
        "rss": "https://seekingalpha.com/api/sa/combined/BABA.xml",
        "icon": "https://seekingalpha.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "中国",
        "priority": 2,
        "description": "阿里巴巴分析与财报相关动态",
    },
    {
        "name": "PDD Earnings SA",
        "name_cn": "拼多多·Seeking Alpha",
        "rss": "https://seekingalpha.com/api/sa/combined/PDD.xml",
        "icon": "https://seekingalpha.com/favicon.ico",
        "category": "财报",
        "doc_type": "earnings",
        "domain": "tech",
        "country": "中国",
        "priority": 2,
        "description": "拼多多分析与财报相关动态",
    },
    {
        "name": "CNINFO Filings",
        "name_cn": "巨潮资讯·公告",
        "rss": _gnews_cn(
            "site:cninfo.com.cn (年报 OR 半年报 OR 季报 OR 公告) when:7d"
        ),
        "icon": "http://www.cninfo.com.cn/favicon.ico",
        "category": "公司公告",
        "doc_type": "announcement",
        "domain": "industry",
        "country": "中国",
        "priority": 1,
        "description": "A股信息披露与公告线索",
    },
    {
        "name": "SSE News",
        "name_cn": "上交所动态",
        "rss": _gnews_cn("site:sse.com.cn (公告 OR 通知 OR 监管) when:14d"),
        "icon": "http://www.sse.com.cn/favicon.ico",
        "category": "公司公告",
        "doc_type": "announcement",
        "domain": "macro",
        "country": "中国",
        "priority": 2,
        "description": "上海证券交易所监管与市场动态",
    },
    # ---------- 研报 ----------
    {
        "name": "Fed Research Hub",
        "name_cn": "美联储研究",
        "rss": _GNEWS_US.format(domain="federalreserve.gov"),
        "icon": "https://www.federalreserve.gov/favicon.ico",
        "category": "研报",
        "doc_type": "research",
        "domain": "macro",
        "country": "美国",
        "priority": 2,
        "description": "美联储研究与工作论文线索",
    },
    {
        "name": "SSRN Economics",
        "name_cn": "SSRN·经济",
        "rss": _gnews_en(
            'site:papers.ssrn.com (economics OR finance OR "working paper") when:14d'
        ),
        "icon": "https://www.ssrn.com/favicon.ico",
        "category": "研报",
        "doc_type": "research",
        "domain": "macro",
        "country": "国际",
        "priority": 2,
        "description": "SSRN 经济金融工作论文线索",
    },
    {
        "name": "World Bank Research Papers",
        "name_cn": "世行研究论文",
        "rss": _gnews_en(
            'site:worldbank.org ("Policy Research Working Paper" OR research) when:30d'
        ),
        "icon": "https://www.worldbank.org/favicon.ico",
        "category": "研报",
        "doc_type": "research",
        "domain": "macro",
        "country": "国际",
        "priority": 2,
        "description": "世界银行政策研究工作论文",
    },
    {
        "name": "OECD Research",
        "name_cn": "OECD研究",
        "rss": _gnews_en(
            "site:oecd.org (working paper OR outlook OR report) when:30d"
        ),
        "icon": "https://www.oecd.org/favicon.ico",
        "category": "研报",
        "doc_type": "research",
        "domain": "macro",
        "country": "国际",
        "priority": 2,
        "description": "经合组织研究与展望",
    },
    # ---------- 白皮书 ----------
    {
        "name": "WEF Reports",
        "name_cn": "世界经济论坛报告",
        "rss": _gnews_en(
            'site:weforum.org (report OR whitepaper OR "global risks") when:60d'
        ),
        "icon": "https://www.weforum.org/favicon.ico",
        "category": "白皮书",
        "doc_type": "whitepaper",
        "domain": "geopolitics",
        "country": "国际",
        "priority": 2,
        "description": "世界经济论坛报告与白皮书",
    },
    {
        "name": "McKinsey Insights",
        "name_cn": "麦肯锡洞见",
        "rss": "https://www.mckinsey.com/insights/rss",
        "icon": "https://www.mckinsey.com/favicon.ico",
        "category": "白皮书",
        "doc_type": "whitepaper",
        "domain": "industry",
        "country": "国际",
        "priority": 1,
        "description": "麦肯锡产业与管理研究报告",
    },
    {
        "name": "Deloitte Insights",
        "name_cn": "德勤洞见",
        "rss": _GNEWS_US.format(domain="www2.deloitte.com"),
        "icon": "https://www2.deloitte.com/favicon.ico",
        "category": "白皮书",
        "doc_type": "whitepaper",
        "domain": "industry",
        "country": "国际",
        "priority": 2,
        "description": "德勤行业洞察与报告线索",
    },
    {
        "name": "IPCC News",
        "name_cn": "IPCC气候",
        "rss": _gnews_en(
            "site:ipcc.ch (report OR assessment OR summary) when:365d"
        ),
        "icon": "https://www.ipcc.ch/favicon.ico",
        "category": "白皮书",
        "doc_type": "whitepaper",
        "domain": "energy",
        "country": "国际",
        "priority": 2,
        "description": "IPCC 评估报告与气候科学综合",
    },
    # ---------- 科学论文 ----------
    {
        "name": "arXiv cs.AI",
        "name_cn": "arXiv·人工智能",
        "rss": "https://rss.arxiv.org/rss/cs.AI",
        "icon": "https://arxiv.org/favicon.ico",
        "category": "科学论文",
        "doc_type": "paper",
        "domain": "tech",
        "country": "国际",
        "priority": 1,
        "description": "人工智能预印本",
    },
    {
        "name": "arXiv cs.CL",
        "name_cn": "arXiv·计算语言学",
        "rss": "https://rss.arxiv.org/rss/cs.CL",
        "icon": "https://arxiv.org/favicon.ico",
        "category": "科学论文",
        "doc_type": "paper",
        "domain": "tech",
        "country": "国际",
        "priority": 1,
        "description": "NLP / 大模型相关预印本",
    },
    {
        "name": "arXiv econ.GN",
        "name_cn": "arXiv·一般经济",
        "rss": "https://rss.arxiv.org/rss/econ.GN",
        "icon": "https://arxiv.org/favicon.ico",
        "category": "科学论文",
        "doc_type": "paper",
        "domain": "macro",
        "country": "国际",
        "priority": 2,
        "description": "经济学预印本",
    },
    {
        "name": "bioRxiv Newest",
        "name_cn": "bioRxiv",
        "rss": "https://connect.biorxiv.org/biorxiv_xml.php?subject=all",
        "icon": "https://www.biorxiv.org/favicon.ico",
        "category": "科学论文",
        "doc_type": "paper",
        "domain": "health",
        "country": "国际",
        "priority": 2,
        "description": "生物学预印本",
    },
    {
        "name": "NEJM",
        "name_cn": "新英格兰医学杂志",
        "rss": "https://www.nejm.org/action/showFeed?jc=nejm&type=etoc&feed=rss",
        "icon": "https://www.nejm.org/favicon.ico",
        "category": "科学论文",
        "doc_type": "paper",
        "domain": "health",
        "country": "美国",
        "priority": 1,
        "description": "临床医学顶刊",
    },
    {
        "name": "PNAS",
        "name_cn": "美国科学院院刊",
        "rss": "https://www.pnas.org/action/showFeed?type=etoc&feed=rss&jc=pnas",
        "icon": "https://www.pnas.org/favicon.ico",
        "category": "科学论文",
        "doc_type": "paper",
        "domain": "tech",
        "country": "美国",
        "priority": 2,
        "description": "综合科学顶刊",
    },
    # ---------- 媒体 ----------
    {
        "name": "TechCrunch",
        "name_cn": "TechCrunch",
        "rss": "https://techcrunch.com/feed/",
        "icon": "https://techcrunch.com/favicon.ico",
        "category": "媒体",
        "doc_type": "media",
        "domain": "tech",
        "country": "美国",
        "priority": 2,
        "description": "科技创业与产业新闻",
    },
    {
        "name": "The Verge",
        "name_cn": "The Verge",
        "rss": "https://www.theverge.com/rss/index.xml",
        "icon": "https://www.theverge.com/favicon.ico",
        "category": "媒体",
        "doc_type": "media",
        "domain": "tech",
        "country": "美国",
        "priority": 2,
        "description": "消费科技与互联网",
    },
    {
        "name": "Caixin Global",
        "name_cn": "财新国际",
        "rss": _gnews_en("site:caixinglobal.com when:7d"),
        "icon": "https://www.caixinglobal.com/favicon.ico",
        "category": "媒体",
        "doc_type": "media",
        "domain": "macro",
        "country": "中国",
        "priority": 1,
        "description": "财新英文报道",
    },
    # ---------- 扩展：能源气候 ----------
    {
        "name": "Carbon Brief",
        "name_cn": "Carbon Brief",
        "rss": "https://www.carbonbrief.org/feed",
        "icon": "https://www.carbonbrief.org/favicon.ico",
        "category": "白皮书",
        "doc_type": "research",
        "domain": "energy",
        "country": "英国",
        "priority": 1,
        "description": "气候科学与政策解读",
    },
    {
        "name": "Ember Climate",
        "name_cn": "Ember",
        "rss": _GNEWS_US.format(domain="ember-climate.org"),
        "icon": "https://ember-climate.org/favicon.ico",
        "category": "数据发布",
        "doc_type": "data",
        "domain": "energy",
        "country": "国际",
        "priority": 1,
        "description": "全球电力与能源转型数据",
    },
    {
        "name": "IRENA News",
        "name_cn": "国际可再生能源署",
        "rss": _GNEWS_US.format(domain="irena.org"),
        "icon": "https://www.irena.org/favicon.ico",
        "category": "国际组织",
        "doc_type": "whitepaper",
        "domain": "energy",
        "country": "国际",
        "priority": 1,
        "description": "IRENA 可再生与能源转型报告线索",
    },
    {
        "name": "Rhodium Group",
        "name_cn": "荣鼎集团",
        "rss": "https://www.rhg.com/feed/",
        "icon": "https://www.rhg.com/favicon.ico",
        "category": "美国智库",
        "doc_type": "think_tank",
        "domain": "energy",
        "country": "美国",
        "priority": 1,
        "description": "气候、宏观与中美政策数据研究",
    },
    {
        "name": "E3G",
        "name_cn": "E3G",
        "rss": "https://www.e3g.org/feed/",
        "icon": "https://www.e3g.org/favicon.ico",
        "category": "英国智库",
        "doc_type": "think_tank",
        "domain": "energy",
        "country": "英国",
        "priority": 2,
        "description": "欧洲气候外交与能源转型智库",
    },
    {
        "name": "EIA Today in Energy",
        "name_cn": "美国能源信息署",
        "rss": "https://www.eia.gov/rss/todayinenergy.xml",
        "icon": "https://www.eia.gov/favicon.ico",
        "category": "数据发布",
        "doc_type": "data",
        "domain": "energy",
        "country": "美国",
        "priority": 1,
        "description": "EIA 每日能源数据与解读",
    },
    # ---------- 扩展：科技治理 / AI 政策 ----------
    {
        "name": "Georgetown CSET",
        "name_cn": "乔治城CSET",
        "rss": _GNEWS_US.format(domain="cset.georgetown.edu"),
        "icon": "https://cset.georgetown.edu/favicon.ico",
        "category": "美国智库",
        "doc_type": "think_tank",
        "domain": "tech",
        "country": "美国",
        "priority": 1,
        "description": "新兴技术安全与对华科技政策",
    },
    {
        "name": "ITIF",
        "name_cn": "信息技术与创新基金会",
        "rss": "https://itif.org/feed/",
        "icon": "https://itif.org/favicon.ico",
        "category": "美国智库",
        "doc_type": "think_tank",
        "domain": "tech",
        "country": "美国",
        "priority": 1,
        "description": "美国科技与产业政策智库",
    },
    {
        "name": "Stanford HAI",
        "name_cn": "斯坦福HAI",
        "rss": _GNEWS_US.format(domain="hai.stanford.edu"),
        "icon": "https://hai.stanford.edu/favicon.ico",
        "category": "认知网站",
        "doc_type": "research",
        "domain": "tech",
        "country": "美国",
        "priority": 1,
        "description": "AI 治理、社会影响与政策研究",
    },
    {
        "name": "OECD AI Policy",
        "name_cn": "OECD·AI政策",
        "rss": _gnews_en('site:oecd.org (AI OR "artificial intelligence" OR "AI policy") when:30d'),
        "icon": "https://www.oecd.org/favicon.ico",
        "category": "国际组织",
        "doc_type": "policy",
        "domain": "tech",
        "country": "国际",
        "priority": 2,
        "description": "OECD 人工智能政策与治理线索",
    },
    # ---------- 扩展：对华与亚太观察 ----------
    {
        "name": "MERICS",
        "name_cn": "墨卡托中国研究中心",
        "rss": _GNEWS_US.format(domain="merics.org"),
        "icon": "https://merics.org/favicon.ico",
        "category": "德国智库",
        "doc_type": "think_tank",
        "domain": "geopolitics",
        "country": "德国",
        "priority": 1,
        "description": "欧洲核心对华政策研究智库",
    },
    {
        "name": "ECFR",
        "name_cn": "欧洲对外关系委员会",
        "rss": "https://ecfr.eu/feed/",
        "icon": "https://ecfr.eu/favicon.ico",
        "category": "欧盟智库",
        "doc_type": "think_tank",
        "domain": "geopolitics",
        "country": "国际",
        "priority": 1,
        "description": "欧洲外交与安全政策分析",
    },
    {
        "name": "SIPRI",
        "name_cn": "斯德哥尔摩国际和平研究所",
        "rss": _GNEWS_US.format(domain="sipri.org"),
        "icon": "https://www.sipri.org/favicon.ico",
        "category": "瑞典智库",
        "doc_type": "think_tank",
        "domain": "geopolitics",
        "country": "瑞典",
        "priority": 1,
        "description": "军备、冲突与和平研究权威",
    },
    {
        "name": "ASPI",
        "name_cn": "澳大利亚战略政策研究所",
        "rss": "https://www.aspi.org.au/feed/",
        "icon": "https://www.aspi.org.au/favicon.ico",
        "category": "澳大利亚智库",
        "doc_type": "think_tank",
        "domain": "geopolitics",
        "country": "澳大利亚",
        "priority": 1,
        "description": "印太安全与对华战略研究",
    },
    {
        "name": "ORF India",
        "name_cn": "观察家研究基金会",
        "rss": _GNEWS_US.format(domain="orfonline.org"),
        "icon": "https://www.orfonline.org/favicon.ico",
        "category": "印度智库",
        "doc_type": "think_tank",
        "domain": "geopolitics",
        "country": "印度",
        "priority": 1,
        "description": "印度外交、安全与经济政策",
    },
    {
        "name": "RSIS Singapore",
        "name_cn": "拉惹勒南国际研究院",
        "rss": _GNEWS_US.format(domain="rsis.edu.sg"),
        "icon": "https://www.rsis.edu.sg/favicon.ico",
        "category": "新加坡智库",
        "doc_type": "think_tank",
        "domain": "geopolitics",
        "country": "新加坡",
        "priority": 1,
        "description": "东南亚安全与战略研究",
    },
    {
        "name": "Prospect Foundation",
        "name_cn": "远景基金会",
        "rss": _GNEWS_US.format(domain="pf.org.tw"),
        "icon": "https://www.pf.org.tw/favicon.ico",
        "category": "台湾智库",
        "doc_type": "think_tank",
        "domain": "geopolitics",
        "country": "台湾",
        "priority": 1,
        "description": "台海与亚太战略观察",
    },
    {
        "name": "INDSR Taiwan",
        "name_cn": "国防安全研究院",
        "rss": _GNEWS_US.format(domain="indsr.org.tw"),
        "icon": "https://www.indsr.org.tw/favicon.ico",
        "category": "台湾智库",
        "doc_type": "think_tank",
        "domain": "geopolitics",
        "country": "台湾",
        "priority": 2,
        "description": "台湾防务与安全研究",
    },
    {
        "name": "Clingendael",
        "name_cn": "克林根达尔国际关系研究所",
        "rss": _GNEWS_US.format(domain="clingendael.org"),
        "icon": "https://www.clingendael.org/favicon.ico",
        "category": "荷兰智库",
        "doc_type": "think_tank",
        "domain": "geopolitics",
        "country": "荷兰",
        "priority": 2,
        "description": "荷兰外交与国际安全研究",
    },
    {
        "name": "RIETI",
        "name_cn": "经济产业研究所",
        "rss": _GNEWS_US.format(domain="rieti.go.jp"),
        "icon": "https://www.rieti.go.jp/favicon.ico",
        "category": "日本智库",
        "doc_type": "think_tank",
        "domain": "macro",
        "country": "日本",
        "priority": 1,
        "description": "日本经济产业政策研究",
    },
    {
        "name": "JIIA",
        "name_cn": "日本国际问题研究所",
        "rss": _GNEWS_US.format(domain="jiia.or.jp"),
        "icon": "https://www.jiia.or.jp/favicon.ico",
        "category": "日本智库",
        "doc_type": "think_tank",
        "domain": "geopolitics",
        "country": "日本",
        "priority": 1,
        "description": "日本外交与国际问题研究",
    },
    # ---------- 扩展：中国补充 ----------
    {
        "name": "RUC National Academy of Development",
        "name_cn": "人大国发院",
        "rss": _gnews_cn("site:nads.ruc.edu.cn OR (人大国发院 OR \"国家发展与战略研究院\") when:30d"),
        "icon": "https://nads.ruc.edu.cn/favicon.ico",
        "category": "中国智库",
        "doc_type": "think_tank",
        "domain": "macro",
        "country": "中国",
        "priority": 1,
        "description": "中国人民大学国家发展与战略研究院",
    },
    {
        "name": "NIFD",
        "name_cn": "国家金融与发展实验室",
        "rss": _gnews_cn("site:nifd.cn OR \"国家金融与发展实验室\" when:30d"),
        "icon": "https://www.nifd.cn/favicon.ico",
        "category": "中国智库",
        "doc_type": "think_tank",
        "domain": "macro",
        "country": "中国",
        "priority": 1,
        "description": "金融宏观与监管研究",
    },
    {
        "name": "Pangoal Think Tank",
        "name_cn": "盘古智库",
        "rss": _gnews_cn("site:pangoal.cn OR 盘古智库 when:30d"),
        "icon": "https://www.pangoal.cn/favicon.ico",
        "category": "中国智库",
        "doc_type": "think_tank",
        "domain": "geopolitics",
        "country": "中国",
        "priority": 2,
        "description": "综合政策与国际问题研究",
    },
    {
        "name": "The Paper Thought",
        "name_cn": "澎湃思想市场",
        "rss": _gnews_cn("site:thepaper.cn (思想市场 OR 澎湃研究所 OR 政经) when:14d"),
        "icon": "https://www.thepaper.cn/favicon.ico",
        "category": "媒体",
        "doc_type": "media",
        "domain": "general",
        "country": "中国",
        "priority": 2,
        "description": "澎湃深度评论与思想类内容线索",
    },
    {
        "name": "Yicai News",
        "name_cn": "第一财经",
        "rss": _gnews_cn("site:yicai.com (宏观 OR 政策 OR 金融 OR 产业) when:7d"),
        "icon": "https://www.yicai.com/favicon.ico",
        "category": "媒体",
        "doc_type": "media",
        "domain": "macro",
        "country": "中国",
        "priority": 2,
        "description": "财经政策与产业新闻线索",
    },
    # ---------- 扩展：宏观 / 卫生 ----------
    {
        "name": "Bank of Japan News",
        "name_cn": "日本银行",
        "rss": "https://www.boj.or.jp/en/rss/whatsnew.xml",
        "icon": "https://www.boj.or.jp/favicon.ico",
        "category": "经济政策",
        "doc_type": "policy",
        "domain": "macro",
        "country": "日本",
        "priority": 1,
        "description": "日本央行政策与公告",
    },
    {
        "name": "UNCTAD News",
        "name_cn": "联合国贸发会议",
        "rss": _GNEWS_US.format(domain="unctad.org"),
        "icon": "https://unctad.org/favicon.ico",
        "category": "国际组织",
        "doc_type": "whitepaper",
        "domain": "macro",
        "country": "国际",
        "priority": 2,
        "description": "贸易、投资与发展报告线索",
    },
    {
        "name": "CDC Newsroom",
        "name_cn": "美国疾控中心",
        "rss": "https://tools.cdc.gov/api/v2/resources/media/132608.rss",
        "icon": "https://www.cdc.gov/favicon.ico",
        "category": "政策文件",
        "doc_type": "policy",
        "domain": "health",
        "country": "美国",
        "priority": 2,
        "description": "CDC 公共卫生新闻室",
    },
    {
        "name": "FDA Press",
        "name_cn": "美国食品药品管理局",
        "rss": (
            "https://www.fda.gov/about-fda/contact-fda/stay-informed/"
            "rss-feeds/press-releases/rss.xml"
        ),
        "icon": "https://www.fda.gov/favicon.ico",
        "category": "政策文件",
        "doc_type": "policy",
        "domain": "health",
        "country": "美国",
        "priority": 2,
        "description": "FDA 新闻稿与监管动态",
    },
]
